---
- name: "Destroy Digital Ocean droplets"
  hosts: localhost
  gather_facts: true
  vars:
    elastic_hosts: "{{ q('inventory_hostnames','elastic_hosts') }}"
  tasks:
    - include_tasks: destroy-digitalocean.yml
      loop: "{{ elastic_hosts }}"
      loop_control:
        loop_var: do_hostname
...