---
- name: "Destroy Digital Ocean droplets"
  hosts: localhost
  tasks:
    - name: "Print current hostname"
      debug: msg="Doing {{ do_hostname }}"
      include_tasks: provision-digitalocean.yml
      loop: "{{ elastic_hosts }}"
      loop_control:
        loop_var: do_hostname
        
        
        
- name: "DO Destroy"
  community.digitalocean.digital_ocean_droplet:
    unique_name: yes
    state: deleted
    name: "{{ do_hostname }}"
    oauth_token: "{{ digio_api_key }}"
    size: "{{ slug }}"
    region: fra1
 #   ssh_keys: "[{{ hostvars['localhost']['pubkey_id'] }}]"
    ssh_keys: "[{{ pubkey_id }}]"
    image: ubuntu-20-04-x64
    wait_timeout: 500
  register: created_droplet

...